### ISSUE TITLE
node.js and npm

### ISSUE THREAD

**Issue by davidjorgensen** [babun/babun#157]
Hello

I am so far loving babun. With some initial setup errors, I finally got it working.
There are still some kinks here and there and I am trying to fix them one at a time.

I have some problems with both node.js and npm. both of which are failing.

``` javascript
net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:660:19)
    at startup (node.js:145:16)
    at node.js:902:3
```

Quick searches reveal something about node.js not working with cygwin.. 

Any thoughts?

This could be a dealbreaker for me, as I have some important developer tools running node.js

**Comment by warrenfalk** [comment]
Thought I'd share the answer given by stack-overflow user, troy, at http://stackoverflow.com/questions/10043177/node-js-cygwin-not-supported

With admin rights, run `dos2unix '/cygdrive/c/Program Files/nodejs/npm'`

That solves many issues, then if you continue to get EINVAL, this can usually be resolved by running a command in the native cygwin shell

`cygstart /bin/bash`

**Comment by tombujok** [comment]
@jlupi does it work for you now?

**Comment by TWGerard** [comment]
It's not ideal, but you can do this with a virtual machine using Vagrant. Check out this vagrant box I've been using:

https://github.com/semmypurewal/node-dev-bootstrap

**Comment by lukecfairchild** [comment]
@elebeaup I could kiss you, that works perfectly.

**Comment by jorgeorpinel** [comment]
@warrenfalk I read about dos2unix elsewhere and yes, that works for me. Thanks
