### ISSUE TITLE
Numpy not working after pact install

### ISSUE THREAD

**Issue by joireman** [babun/babun#231]
After installing python-numpy with pact, attempting to import numpy in a python session gives an ImportError 

```
    [06:37 AM]:~-> python
    Python 2.7.3 (default, Dec 18 2012, 13:50:09)
    [GCC 4.5.3] on cygwin
     Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
        import add_newdocs
      File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
        from numpy.lib import add_newdoc
      File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 13, in <module>
        from polynomial import *
      File "/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 17, in <module>
        from numpy.linalg import eigvals, lstsq, inv
      File "/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 48, in <module>
        from linalg import *
      File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 23, in <module>
        from numpy.linalg import lapack_lite
    ImportError: No such process
```

It seems like this might be related to http://www.mail-archive.com/cygwin@cygwin.com/msg115535.html but numpy is unusable.   Is there a way to have babun call out to a different python version installed on the local machine that has a working numpy/scipy stack (scipy isn't available through pact AFAIK)

**Comment by tombujok** [comment]
Fixed in 1.1.0. 
Release status: #266
