### ISSUE TITLE
cannot run npm install

### ISSUE THREAD

**Issue by ieiayaobb** [babun/babun#399]
{ ant-design } master » npm install                                                         /cygdrive/d/workspace/ant-design
npm WARN peerDependencies The peer dependency jshint@ included from precommit-hook will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> precommit-hook@1.0.7 install D:\workspace\ant-design\node_modules\precommit-hook
> hook_install

Creating .git/hooks...
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'D:\cygdrive\d\workspace\ant-design\.git\hooks'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at D:\workspace\ant-design\node_modules\precommit-hook\bin\install:26:20
    at D:\workspace\ant-design\node_modules\precommit-hook\utils.js:11:9
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN prefer global babel@5.6.23 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! precommit-hook@1.0.7 install: `hook_install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the precommit-hook@1.0.7 install script 'hook_install'.
npm ERR! This is most likely a problem with the precommit-hook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hook_install
npm ERR! You can get their info via:
npm ERR!     npm owner ls precommit-hook
npm ERR! There is likely additional logging output above.

> precommit-hook@1.0.7 uninstall D:\workspace\ant-design\node_modules\precommit-hook
> hook_uninstall

Removing .git/hooks/pre-commit...
fs.js:883
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'D:\cygdrive\d\workspace\ant-design\.git\hooks\pre-commit'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:883:18)
    at D:\workspace\ant-design\node_modules\precommit-hook\bin\uninstall:12:12
    at D:\workspace\ant-design\node_modules\precommit-hook\utils.js:11:9
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN continuing anyway precommit-hook@1.0.7 uninstall: `hook_uninstall`
npm WARN continuing anyway Exit status 1

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\ant-design\npm-debug.log

As you saw, when I try to execute "npm install", it will display these error messages.
And after I change to the default CMD, it runs well.

**Comment by Alex-D** [comment]
Have you try `npm install /d/workspace/ant-design` ?

**Comment by TWGerard** [comment]
Have you tried `--no-bin-links`?
