### ISSUE TITLE
Numpy still not working (babun 1.2.0)

### ISSUE THREAD

**Issue by JillZhang** [babun/babun#684]
The python package still cannot be imported in the newest babun. I already set the PYTHONAPAPTH to "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/", where holds all packages.

Can anyone help me with that?
Thanks!
» python                                                                                                           /cygdrive/c/Users/jzhang1271/Downloads
Python 2.7.8 (default, Jul 28 2014, 01:34:03)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/cygdrive/c/Users/jzhang1271/appdata/local/continuum/anaconda2/lib/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray

**Comment by AnthonyWC** [comment]
Works for me...

```
antho@stratus  ~/devops  python
Python 2.7.10 (default, Jun  1 2015, 18:17:45)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>>
```

but if you are using anaconda just use Jupyter notebook.

**Comment by amoose136** [comment]
I just made a fresh install of babun and first tried installing pip to manage numpy. Installed but python didn't see it. Then I tried using pact. It installed but python gave some import errors.

```
{ ~ }  » python                                                                                 ~
Python 2.7.8 (default, Jul 28 2014, 01:34:03)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: No such process
>>>
```

**Comment by retif** [comment]
+1 for ImportError: cannot import name multiarray for python 3
