### ISSUE TITLE
MySQL Python package installation error

### ISSUE THREAD

**Issue by elelement** [babun/babun#703]
Hi. I can't install mysql package in Babun.
My environment is:

- Windows 7
- Python 2.7

Trace:

```bash
» pip install mysql                                                                                                                           /lib/mysql
Collecting mysql
  Using cached mysql-0.0.1.tar.gz
Collecting MySQL-python (from mysql)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c2lHSu/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

I've been searching through Google and the most accepted solution is to install libmysqlclient-devel, but it didn't solve the issue.

Any thoughts? Is this an issue or maybe I'm missing something.

Thanks

**Comment by elelement** [comment]
Installing additional packages solved the issue: 

```bash
 pact install libmysqld-devel libmysqlclient-devel
```

Closing, sorry for the inconvenience.
