### ISSUE TITLE
Npm concurrently package does not run correctly

### ISSUE THREAD

**Issue by Tichau** [babun/babun#704]
Package: https://www.npmjs.com/package/concurrently
Error generated when trying to use concurrently command:
```
Error: spawn /bin/zsh ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3

```

The command works well with the node.js console.

**Comment by Slapbox** [comment]
Also having the same issue. Running the code works fine in Powershell. Seems all but confirmed this is a bug that is babun specific.

**Comment by guyspronck** [comment]
Also experiencing this issue here. Tried changing to /bin/bash but it didn't help

**Comment by mateodelnorte** [comment]
+1

**Comment by finbarmaginn** [comment]
+1

running the commands i want are working fine in separate terminals, try using concurrently and i get the same issue. also using babun

```
Error: spawn /bin/zsh ENOENT
     at exports._errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3

```

**Comment by guyspronck** [comment]
It's been two months, has anyone found a way around this issue? It's the only thing that makes me go back to the old command prompt for running tests etc.
